name: Deploy to Self-Hosted VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Self-Hosted VPS
        run: |
          ssh -i ~/.ssh/github-actions -p ${{ secrets.SSH_PORT }} -v ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.SSH_PATH }}
            git pull origin master
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml build --no-cache
            docker compose -f docker-compose.yml up -d
            docker system prune -f
          EOF
